import type { CodeAnalysis, CodebaseAnalysis, LLMClient } from "../llm/index.js";

export interface DocumentationTemplate {
  name: string;
  content: string;
}

export const templates: Record<string, DocumentationTemplate> = {
  changeSummary: {
    name: "Change Summary",
    content: `---
title: {{title}}
date: {{date}}
pr: {{prNumber}}
author: {{author}}
---

# Change Summary

## Overview

{{summary}}

## Changes

{{#each changes}}
### {{component}}

- **Type**: {{type}}
- **Impact**: {{impact}}
- **Description**: {{description}}

{{/each}}

## Related Links

- [Source PR]({{prUrl}})
`,
  },
  apiDocumentation: {
    name: "API Documentation",
    content: `---
title: API Documentation - {{component}}
date: {{date}}
---

# {{component}} API

## Overview

{{description}}

## Endpoints

{{endpoints}}

## Related Diagrams

{{diagrams}}
`,
  },
  architectureUpdate: {
    name: "Architecture Update",
    content: `---
title: Architecture Update
date: {{date}}
pr: {{prNumber}}
---

# Architecture Update

## Summary

{{summary}}

## Diagram

\`\`\`mermaid
{{diagram}}
\`\`\`

## Impact

{{impact}}
`,
  },
};

export interface GeneratedDocument {
  filename: string;
  content: string;
  template: string;
}

export function generateFilename(
  analysis: CodeAnalysis,
  prNumber: number,
  template: string
): string {
  const date = new Date().toISOString().split("T")[0];
  const slug = analysis.summary
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .slice(0, 50);
  return `${date}-pr-${prNumber}-${template}-${slug}.md`;
}

export function renderTemplate(
  template: string,
  data: Record<string, unknown>
): string {
  let result = template;

  for (const [key, value] of Object.entries(data)) {
    const regex = new RegExp(`{{${key}}}`, "g");
    result = result.replace(regex, String(value));
  }

  return result;
}

export interface RepoInfo {
  owner: string;
  repo: string;
  branch: string;
}

export function generateProjectDocumentation(
  analysis: CodebaseAnalysis,
  repoInfo: RepoInfo
): string {
  const date = new Date().toISOString().split("T")[0];

  const componentsSection = analysis.components
    .map((c) => {
      const responsibilities = c.responsibilities
        .map((r) => `  - ${r}`)
        .join("\n");
      const dependencies = c.dependencies.length > 0
        ? `\n**Dependencies:** ${c.dependencies.join(", ")}`
        : "";
      return `### ${c.name}

${c.description}

**Responsibilities:**
${responsibilities}${dependencies}`;
    })
    .join("\n\n");

  const externalSystemsSection = analysis.externalSystems.length > 0
    ? analysis.externalSystems
        .map((s) => `- **${s.name}**: ${s.description} (${s.integration})`)
        .join("\n")
    : "No external system integrations documented.";

  const technologiesSection = analysis.technologies
    .map((t) => `- ${t}`)
    .join("\n");

  return `---
title: ${repoInfo.repo} Documentation
date: ${date}
repository: ${repoInfo.owner}/${repoInfo.repo}
branch: ${repoInfo.branch}
---

# ${repoInfo.repo}

${analysis.summary}

## Overview

${analysis.purpose}

## Architecture

${analysis.architecture}

## Components

${componentsSection}

## External Systems

${externalSystemsSection}

## Technologies

${technologiesSection}

## Getting Started

${analysis.gettingStarted}

## Configuration

${analysis.configuration}

---

*Documentation generated by [DocSync](https://github.com/your-org/docsync) on ${date}*
`;
}

export async function generateC4Diagrams(
  llmClient: LLMClient,
  analysis: CodebaseAnalysis
): Promise<{ context: string; container: string; component: string }> {
  const [context, container, component] = await Promise.all([
    llmClient.generateCodebaseDiagram(analysis, "context"),
    llmClient.generateCodebaseDiagram(analysis, "container"),
    llmClient.generateCodebaseDiagram(analysis, "component"),
  ]);

  return { context, container, component };
}
