import { SlackNotificationError, withRetry, logger } from "../errors/index.js";

export interface SlackNotificationOptions {
  docsPR: {
    number: number;
    url: string;
    title: string;
  };
  sourcePR: {
    number: number;
    url: string;
    title: string;
    repository: string;
  };
  summary: string;
  filesChanged: string[];
  reviewers: string[];
}

export interface SlackClient {
  webhookUrl: string;
  channel?: string;
  maxRetries: number;
}

interface SlackBlock {
  type: string;
  text?: {
    type: string;
    text: string;
    emoji?: boolean;
  };
  elements?: Array<{
    type: string;
    text?: string;
    url?: string;
  }>;
  fields?: Array<{
    type: string;
    text: string;
  }>;
}

interface SlackMessage {
  channel?: string;
  blocks: SlackBlock[];
}

export function createSlackClient(
  webhookUrl: string,
  options?: { channel?: string; maxRetries?: number }
): SlackClient {
  return {
    webhookUrl,
    channel: options?.channel,
    maxRetries: options?.maxRetries ?? 3,
  };
}

export function formatMessage(
  options: SlackNotificationOptions,
  channel?: string
): SlackMessage {
  const blocks: SlackBlock[] = [
    {
      type: "header",
      text: {
        type: "plain_text",
        text: "Documentation PR Created",
        emoji: true,
      },
    },
    {
      type: "section",
      text: {
        type: "mrkdwn",
        text: `*<${options.docsPR.url}|${options.docsPR.title}>*`,
      },
    },
    {
      type: "section",
      fields: [
        {
          type: "mrkdwn",
          text: `*Source PR:*\n<${options.sourcePR.url}|#${options.sourcePR.number} - ${options.sourcePR.title}>`,
        },
        {
          type: "mrkdwn",
          text: `*Repository:*\n${options.sourcePR.repository}`,
        },
      ],
    },
    {
      type: "section",
      text: {
        type: "mrkdwn",
        text: `*Summary:*\n${options.summary}`,
      },
    },
  ];

  if (options.filesChanged.length > 0) {
    const filesText =
      options.filesChanged.length <= 5
        ? options.filesChanged.map((f) => `\`${f}\``).join(", ")
        : `${options.filesChanged
            .slice(0, 5)
            .map((f) => `\`${f}\``)
            .join(", ")} and ${options.filesChanged.length - 5} more`;

    blocks.push({
      type: "section",
      text: {
        type: "mrkdwn",
        text: `*Files Changed:*\n${filesText}`,
      },
    });
  }

  if (options.reviewers.length > 0) {
    blocks.push({
      type: "section",
      text: {
        type: "mrkdwn",
        text: `*Reviewers:*\n${options.reviewers.join(", ")}`,
      },
    });
  }

  blocks.push({
    type: "context",
    elements: [
      {
        type: "mrkdwn",
        text: `Generated by DocSync at ${new Date().toISOString()}`,
      },
    ],
  });

  const message: SlackMessage = { blocks };
  if (channel) {
    message.channel = channel;
  }

  return message;
}

export async function sendNotification(
  client: SlackClient,
  options: SlackNotificationOptions
): Promise<void> {
  logger.info("Sending Slack notification", {
    docsPRNumber: options.docsPR.number,
    sourcePRNumber: options.sourcePR.number,
  });

  const message = formatMessage(options, client.channel);

  return withRetry(
    async () => {
      try {
        const response = await fetch(client.webhookUrl, {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
          },
          body: JSON.stringify(message),
        });

        if (!response.ok) {
          const errorText = await response.text();
          throw new SlackNotificationError(
            `Failed to send Slack notification: ${errorText}`,
            {
              statusCode: response.status,
              docsPRNumber: options.docsPR.number,
            }
          );
        }

        logger.info("Slack notification sent successfully", {
          docsPRNumber: options.docsPR.number,
        });
      } catch (error) {
        if (error instanceof SlackNotificationError) {
          throw error;
        }
        const message = error instanceof Error ? error.message : String(error);
        throw new SlackNotificationError(
          `Failed to send Slack notification: ${message}`,
          {
            docsPRNumber: options.docsPR.number,
          }
        );
      }
    },
    { maxRetries: client.maxRetries }
  );
}
