export interface PRCreationOptions {
  owner: string;
  repo: string;
  title: string;
  body: string;
  head: string;
  base: string;
  reviewers?: string[];
}

export interface CreatedPR {
  number: number;
  url: string;
  title: string;
}

export interface GitHubAPIClient {
  token: string;
  baseUrl: string;
}

interface GitHubPRResponse {
  number: number;
  html_url: string;
  title: string;
}

export function createGitHubClient(token: string): GitHubAPIClient {
  return {
    token,
    baseUrl: "https://api.github.com",
  };
}

export async function createPullRequest(
  client: GitHubAPIClient,
  options: PRCreationOptions
): Promise<CreatedPR> {
  const { owner, repo, title, body, head, base } = options;

  const response = await fetch(
    `${client.baseUrl}/repos/${owner}/${repo}/pulls`,
    {
      method: "POST",
      headers: {
        Authorization: `Bearer ${client.token}`,
        Accept: "application/vnd.github.v3+json",
        "Content-Type": "application/json",
      },
      body: JSON.stringify({ title, body, head, base }),
    }
  );

  if (!response.ok) {
    const error = await response.text();
    throw new Error(`Failed to create PR: ${error}`);
  }

  const data = (await response.json()) as GitHubPRResponse;

  if (options.reviewers && options.reviewers.length > 0) {
    await addReviewers(client, owner, repo, data.number, options.reviewers);
  }

  return {
    number: data.number,
    url: data.html_url,
    title: data.title,
  };
}

export async function addReviewers(
  client: GitHubAPIClient,
  owner: string,
  repo: string,
  prNumber: number,
  reviewers: string[]
): Promise<void> {
  const response = await fetch(
    `${client.baseUrl}/repos/${owner}/${repo}/pulls/${prNumber}/requested_reviewers`,
    {
      method: "POST",
      headers: {
        Authorization: `Bearer ${client.token}`,
        Accept: "application/vnd.github.v3+json",
        "Content-Type": "application/json",
      },
      body: JSON.stringify({ reviewers }),
    }
  );

  if (!response.ok) {
    const error = await response.text();
    console.error(`Failed to add reviewers: ${error}`);
  }
}

export function generatePRDescription(
  sourcePR: { number: number; title: string; url: string },
  filesChanged: string[],
  summary: string
): string {
  return `## Documentation Update

This PR contains automatically generated documentation updates based on [PR #${sourcePR.number}](${sourcePR.url}).

### Summary

${summary}

### Files Changed

${filesChanged.map((f) => `- \`${f}\``).join("\n")}

### Source

- **Source PR**: [#${sourcePR.number} - ${sourcePR.title}](${sourcePR.url})

---
*Generated by DocSync*
`;
}
