import { PRCreationError, withRetry, logger } from "../errors/index.js";

export interface PRCreationOptions {
  owner: string;
  repo: string;
  title: string;
  body: string;
  head: string;
  base: string;
  reviewers?: string[];
}

export interface CreatedPR {
  number: number;
  url: string;
  title: string;
}

export interface GitHubAPIClient {
  token: string;
  baseUrl: string;
  maxRetries: number;
}

interface GitHubPRResponse {
  number: number;
  html_url: string;
  title: string;
}

export function createGitHubClient(token: string, maxRetries?: number): GitHubAPIClient {
  return {
    token,
    baseUrl: "https://api.github.com",
    maxRetries: maxRetries ?? 3,
  };
}

export async function createPullRequest(
  client: GitHubAPIClient,
  options: PRCreationOptions
): Promise<CreatedPR> {
  const { owner, repo, title, body, head, base } = options;

  logger.info("Creating pull request", { owner, repo, title, head, base });

  return withRetry(
    async () => {
      try {
        const response = await fetch(
          `${client.baseUrl}/repos/${owner}/${repo}/pulls`,
          {
            method: "POST",
            headers: {
              Authorization: `Bearer ${client.token}`,
              Accept: "application/vnd.github.v3+json",
              "Content-Type": "application/json",
            },
            body: JSON.stringify({ title, body, head, base }),
          }
        );

        if (!response.ok) {
          const errorText = await response.text();
          throw new PRCreationError(
            `Failed to create PR: ${errorText}`,
            {
              owner,
              repo,
              statusCode: response.status,
              head,
              base,
            }
          );
        }

        const data = (await response.json()) as GitHubPRResponse;

        if (options.reviewers && options.reviewers.length > 0) {
          await addReviewers(client, owner, repo, data.number, options.reviewers);
        }

        logger.info("Pull request created successfully", {
          owner,
          repo,
          prNumber: data.number,
          url: data.html_url,
        });

        return {
          number: data.number,
          url: data.html_url,
          title: data.title,
        };
      } catch (error) {
        if (error instanceof PRCreationError) {
          throw error;
        }
        const message = error instanceof Error ? error.message : String(error);
        throw new PRCreationError(`Failed to create PR: ${message}`, {
          owner,
          repo,
          head,
          base,
        });
      }
    },
    { maxRetries: client.maxRetries }
  );
}

export async function addReviewers(
  client: GitHubAPIClient,
  owner: string,
  repo: string,
  prNumber: number,
  reviewers: string[]
): Promise<void> {
  logger.info("Adding reviewers to PR", { owner, repo, prNumber, reviewers });

  return withRetry(
    async () => {
      try {
        const response = await fetch(
          `${client.baseUrl}/repos/${owner}/${repo}/pulls/${prNumber}/requested_reviewers`,
          {
            method: "POST",
            headers: {
              Authorization: `Bearer ${client.token}`,
              Accept: "application/vnd.github.v3+json",
              "Content-Type": "application/json",
            },
            body: JSON.stringify({ reviewers }),
          }
        );

        if (!response.ok) {
          const errorText = await response.text();
          throw new PRCreationError(
            `Failed to add reviewers: ${errorText}`,
            {
              owner,
              repo,
              prNumber,
              reviewers,
              statusCode: response.status,
            }
          );
        }

        logger.info("Reviewers added successfully", { owner, repo, prNumber, reviewers });
      } catch (error) {
        if (error instanceof PRCreationError) {
          throw error;
        }
        const message = error instanceof Error ? error.message : String(error);
        throw new PRCreationError(`Failed to add reviewers: ${message}`, {
          owner,
          repo,
          prNumber,
          reviewers,
        });
      }
    },
    { maxRetries: client.maxRetries }
  );
}

export function generatePRDescription(
  sourcePR: { number: number; title: string; url: string },
  filesChanged: string[],
  summary: string
): string {
  return `## Documentation Update

This PR contains automatically generated documentation updates based on [PR #${sourcePR.number}](${sourcePR.url}).

### Summary

${summary}

### Files Changed

${filesChanged.map((f) => `- \`${f}\``).join("\n")}

### Source

- **Source PR**: [#${sourcePR.number} - ${sourcePR.title}](${sourcePR.url})

---
*Generated by DocSync*
`;
}
