import express from "express";
import fs from "fs/promises";
import path from "path";
import { loadConfig } from "./config/index.js";
import { createWebhookRouter, PullRequestEvent } from "./webhook/index.js";
import { GitClient } from "./git/index.js";
import { createLLMClient } from "./llm/index.js";
import { createGitHubClient, createPullRequest } from "./pr/index.js";
import { createOnboardRouter } from "./onboard/index.js";
import { createSlackClient, sendNotification } from "./slack/index.js";
import { logger } from "./errors/index.js";

async function main() {
  const config = loadConfig();

  const gitClient = new GitClient({ token: config.github.token });
  const llmClient = createLLMClient(config.llm);
  const githubClient = createGitHubClient(config.github.token);

  const handleWebhook = async (event: PullRequestEvent) => {
    console.log(`Processing PR #${event.pullRequest.number} from ${event.repository.fullName}`);

    // Clone source repository and get the diff
    const { git } = await gitClient.clone({
      owner: event.repository.owner,
      repo: event.repository.name,
    });

    const diff = await gitClient.getDiff(
      git,
      event.pullRequest.base.sha,
      event.pullRequest.head.sha
    );

    const analysis = await llmClient.analyzeCode(
      diff.files.map((f) => f.patch).join("\n")
    );

    // Clone docs repository
    const { git: docsGit, path: docsPath } = await gitClient.clone({
      owner: config.docsRepository.owner,
      repo: config.docsRepository.repo,
    });

    // Check if documentation exists for this repository
    const docFilename = `${event.repository.name}.md`;
    const docFilePath = path.join(docsPath, "docs", docFilename);

    let existingDocs: string | null = null;
    try {
      existingDocs = await fs.readFile(docFilePath, "utf-8");
    } catch {
      // Documentation doesn't exist yet
      console.log(`No existing documentation found for ${event.repository.fullName}. Consider running onboarding first.`);
    }

    let updatedContent: string;
    let commitMessage: string;

    if (existingDocs) {
      // Update existing documentation
      updatedContent = await llmClient.updateDocumentation(existingDocs, analysis, {
        number: event.pullRequest.number,
        title: event.pullRequest.title,
        author: event.pullRequest.author,
      });
      commitMessage = `docs: Update ${event.repository.name} documentation for PR #${event.pullRequest.number}`;
    } else {
      // No existing docs - create minimal update notice
      const date = new Date().toISOString().split("T")[0];
      updatedContent = `---
title: ${event.repository.name} Documentation
date: ${date}
repository: ${event.repository.fullName}
---

# ${event.repository.name}

> This documentation was auto-generated. Run the onboarding process for comprehensive documentation.

## Recent Changes

### PR #${event.pullRequest.number}: ${event.pullRequest.title}

**Author:** ${event.pullRequest.author}
**Date:** ${date}

${analysis.summary}

### Changes

${analysis.changes.map((c) => `- **${c.component}** (${c.type}): ${c.description}`).join("\n")}
`;
      commitMessage = `docs: Add initial documentation for ${event.repository.name} from PR #${event.pullRequest.number}`;
    }

    // Create branch and write updated documentation
    const branchName = `docs/update-${event.repository.name}-pr-${event.pullRequest.number}`;
    await gitClient.createBranch(docsGit, branchName);

    // Ensure docs directory exists
    await fs.mkdir(path.join(docsPath, "docs"), { recursive: true });
    await fs.writeFile(docFilePath, updatedContent);

    await gitClient.commitAndPush(docsGit, commitMessage, [`docs/${docFilename}`]);

    // Create PR
    const prBody = `## Documentation Update

This PR updates the documentation for **${event.repository.fullName}** based on [PR #${event.pullRequest.number}](https://github.com/${event.repository.fullName}/pull/${event.pullRequest.number}).

### Summary

${analysis.summary}

### Changes

${analysis.changes.map((c) => `- **${c.component}** (${c.type}, ${c.impact} impact): ${c.description}`).join("\n")}

${analysis.architecturalChanges ? "**Note:** This PR includes architectural changes that may affect diagrams." : ""}

---
*Generated by DocSync*
`;

    const pr = await createPullRequest(githubClient, {
      owner: config.docsRepository.owner,
      repo: config.docsRepository.repo,
      title: `docs: Update ${event.repository.name} documentation for PR #${event.pullRequest.number}`,
      body: prBody,
      head: branchName,
      base: config.docsRepository.branch,
      reviewers: [event.pullRequest.author],
    });

    console.log(`Created documentation PR: ${pr.url}`);

    // Send Slack notification if enabled
    if (config.slack?.enabled && config.slack.webhookUrl) {
      try {
        const slackClient = createSlackClient(config.slack.webhookUrl, {
          channel: config.slack.channel,
        });

        await sendNotification(slackClient, {
          docsPR: {
            number: pr.number,
            url: pr.url,
            title: pr.title,
          },
          sourcePR: {
            number: event.pullRequest.number,
            url: `https://github.com/${event.repository.fullName}/pull/${event.pullRequest.number}`,
            title: event.pullRequest.title,
            repository: event.repository.fullName,
          },
          summary: analysis.summary,
          filesChanged: [`docs/${docFilename}`],
          reviewers: [event.pullRequest.author],
        });

        logger.info("Slack notification sent successfully", { prNumber: pr.number });
      } catch (error) {
        // Log error but don't fail the webhook - Slack notification is non-critical
        logger.error("Failed to send Slack notification", error, {
          prNumber: pr.number,
        });
      }
    }
  };

  const app = express();
  app.use(createWebhookRouter(config.webhookSecret, handleWebhook));
  app.use(
    createOnboardRouter({
      gitClient,
      llmClient,
      githubClient,
      docsRepository: config.docsRepository,
    })
  );

  app.get("/health", (_, res) => {
    res.json({ status: "ok" });
  });

  app.listen(config.port, () => {
    console.log(`DocSync server running on port ${config.port}`);
  });
}

main().catch(console.error);
